title: Andrei Epure
author: andreiepure
email: epure _dot_ andrei -at- gmail _dot_ com
description: > # this means to ignore newlines until "baseurl:"
  Andrei Epure, Software Engineer. 

# social links
twitter_username: andrei_cs_pub
github_username:  andreiepure

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
